{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select id as metric, date_eol, 'ok' as state\nfrom versions\n"
    }
   ]
  },
  {
   "title": "Number of parsed Linux releases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select row_number() over (order by updated_at), updated_at from versions\nwhere processed = true;\n"
    },
    {
     "rawSql": "select\n  count(id), now() as time\nfrom\n  versions"
    }
   ]
  },
  {
   "title": "Number of Linux releases per major version",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select prefix, count(id) from(\n                         select id, split_part(id, '.', 1) as prefix from versions\n                                                                     where id !~* 'pre'\n                     )\n                     group by prefix\norder by prefix\n\n"
    }
   ]
  },
  {
   "title": "Number of config entries per version",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select version, count(kconfig_group_id)\nfrom kconfigs_and_versions\n         left join versions\n                   on versions.id = kconfigs_and_versions.version\ngroup by version, published_on\norder by published_on"
    }
   ]
  },
  {
   "title": "New Kconfig entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=\"kconfigs\"} - pg_stat_database_tup_deleted{datname=\"kconfigs\"} - pg_stat_database_tup_deleted{datname=\"kconfigs\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inserts/Delete",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=\"kconfigs\"}",
     "legendFormat": "Insertions"
    },
    {
     "expr": " pg_stat_database_tup_deleted{datname=\"kconfigs\"}",
     "legendFormat": "Deletions"
    },
    {
     "expr": "pg_stat_database_tup_inserted{datname=\"kconfigs\"} - pg_stat_database_tup_deleted{datname=\"kconfigs\"}",
     "legendFormat": "Inserted - deleted"
    }
   ]
  },
  {
   "title": "Number of kconfig entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select row_number() over (order by updated_at), updated_at from kconfig;\n"
    }
   ]
  },
  {
   "title": "Number of kconfig entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select row_number() over (order by created_at), created_at from kconfig;\n"
    }
   ]
  }
 ]
}